development:
  host: localhost
  database: sanderstead_parish_development

test:
  host: localhost
  database: sanderstead_parish_test

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        connect_timeout: 15
